# This is just basically the environment that the settings apply to.
# It's recommended that you only modify the production settings and
# run the application in a production environment.  I recommend
# copying over the development settings to the production settings.
development: &default
  # The name of the forum.  Kind of self-descriptive.  Appears at the
  # top and bottom, and whenever it talks about itself.
  forum_name: "{generic forums}"
  # The version of the forum.  You may not want this to appear or
  # something, so this is open to modification.  You don't need to
  # though.
  forum_version: 0.2.1
  # The maximum amount of times AuthLogic will allow a user to try to
  # login.  Set to 0 to disable.
  max_login_tries: 5
  # The timeout between exceeding amount of login tries.  Set to 0 for
  # a permanent ban.  This is in seconds.
  exceed_login_timeout: 1800
  # The default format to use.  This is recommended to stay as
  # markdown, as the markdown parser is supposedly faster than the
  # bbcode one.
  default_format: markdown
  # Default user options.
  user_options:
    # settings for the boards per page.
    boards_per_page: 20
    # Settings for the threads per page.
    threads_per_page: 20
    # Settings for the posts per page.
    posts_per_page: 20
    # This is whether or not a user wants to show up as 'online'.
    show_online: true
  # The default groups that a registering user belongs to.  This
  # basically defines the groups that most users on the site will have
  # (unless you use a cron or such to remove groups).
  default_user_groups:
    - guest # So the user inherits all of the guest properties
            # This includes negation, so be careful!
    - user
  # The primary group of a user is where the title name and the
  # username's color comes from, as well as avatar size.
  default_primary_group: user
  # The amount, in seconds, from a user's last request that a user is
  # still considered 'online'.
  online: 600
  # Markdown options for RDiscount.  Check
  # https://github.com/rtomayko/rdiscount/ and
  # https://github.com/rtomayko/rdiscount/blob/master/lib/rdiscount.rb
  # for available options.
  markdown_options:
    - :autolink
    - :fenced_code_blocks
    - :no_intra_emphasis
    - :strikethrough
    - :space_after_headers
    - :superscript

  # Allow parameterization of board/thread/post urls.  This makes them
  # look pretty; for example, with the board "primary" and the thread
  # "thread", the url would look like
  #   /boards/1-primary/threads/2-thread/posts
  # With both enabled.
  parameterization:
    # Allow it for threads.
    thread: true
    # Allow it for boards.
    board: true
  # Some settings for avatars.
  avatars:
    # The maximum size that avatars are allowed for.  This is in bytes.
    # Don't ask me why.
    max_size: 104857
    # The allowed content types for avatars.  This can be a single
    # string or an array of content types.
    allowed_content_types:
      - image/jpeg
      - image/png
      - image/gif

production:
  <<: *default
